<?php
/**
 * @file
 * Post new forum questions to the backdrop-issues gitter channel.
 */

/**
 * Implements hook_node_insert().
 */
function borg_gitter_node_insert($node) {
  if ($node->type == 'forum_topic') {
    // Save the node so path properties get created.
      // @todo this might cause problems. Can we do this another way?
    $node->save();
    global $settings;
    $token = $settings['gitter_token'];
    $authorization = 'Authorization: Bearer ' . $token;
    $url = 'https://api.gitter.im/v1/rooms/5639adc616b6c7089cb96941/chatMessages';
    $message = "New forum post: **[$node->title](https://forum.backdropcms.org/{$node->path['alias']})**. Feedback, assistance, comments, etc. welcome. Jump in! :smile: :heart:";
    $payload = array('text' => $message);
    $payload = json_encode($payload);
    // Initiate a curl session.
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_HTTPHEADER,
      array(
        'Content-Type: application/json',
        'Accept: application/json',
        $authorization,
      )
    );
    curl_setopt ($ch, CURLOPT_USERAGENT, 'Mozilla/4.0 (compatible; MSIE 5.01; Windows NT 5.0)');
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $payload);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
    curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 1);
    curl_setopt($ch, CURLOPT_HEADER, 1);
    $content = curl_exec($ch);
    curl_close($ch);
  }
}
