<?php
/**
 * @file
 * The borg_gitter module posts new forum posts to gitter.
 */

/**
 * Implements hook_node_insert().
 */
function borg_gitter_node_insert($node) {
  if ($node->type === 'forum_topic') {
		// Save the node so path properties get created.
		$node->save();
    global $settings;
    $token = $settings['gitter_token'];
    $authorization = 'Authorization: Bearer ' . $token;
    $url = 'https://api.gitter.im/v1/rooms/5639adc616b6c7089cb96941/chatMessages';
    $message = "A new post is on the forum: **$node->title**: https://forum.backdropcms.org/{$node->path['alias']}\n\n Pitching in on the forum is a great way to feel good and contribute to the Backrop Community.\n\n :smile: :heart: :smile:";
    $payload = [
      'text' => $message,
    ];
    $payload = json_encode($payload);
    // Initiate a curl session.
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_HTTPHEADER,
      array(
        'Content-Type: application/json',
	  		'Accept: application/json',
        $authorization,
      )
    );
    curl_setopt ($ch, CURLOPT_USERAGENT, 'Mozilla/4.0 (compatible; MSIE 5.01; Windows NT 5.0)');
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $payload);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
    curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 1);
    curl_setopt($ch, CURLOPT_HEADER, 1);
    $content = curl_exec($ch);
    curl_close($ch);
  }
}
