<?php

/**
 * @file
 * Provides additional functions for Backdrop.org discussion forums.
 */


/**
 * Implements hook_autoload_info().
 */
function borg_forum_autoload_info() {
  return array(
    'taxonomy_term_data_handler_field_last_comment' => 'views/taxonomy_term_data_handler_field_last_comment.inc',
  );
}

/**
 * Implements hook_views_api().
 */
function borg_forum_views_api() {
  return array(
    'api' => 3,
    'path' => backdrop_get_path('module', 'borg_forum') . '/views',
  );
}

/**
 * Implements hook_config_info().
 */
function borg_forum_config_info() {
  $prefixes['borg_forum.settings'] = array(
    'label' => t('Borg forum settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * Stores last comment timestamps.
 */
function borg_forum_last_comment_timestamp($tid) {
  $cache = &backdrop_static(__FUNCTION__, '');
  if (isset($cache[$tid])) {
    return $cache[$tid];
  }

  $results = db_query('SELECT t.tid AS tid, nc.last_comment_timestamp AS last_comment_timestamp FROM {taxonomy_index} t LEFT JOIN {node_comment_statistics} nc ON t.nid = nc.nid')->fetchAll();

  foreach ($results as $result) {
    $cache[$result->tid] = (isset($result->last_comment_timestamp)) ? $result->last_comment_timestamp : NULL;
  }

  return ($cache[$tid]);
}

/**
 * Implements hook_node_view().
 */
function borg_forum_node_view(Node $node, $view_mode, $langcode) {
  if ($node->type == 'forum_topic') {
    $breadcrumb = array();
    $breadcrumb[] = l(t('Home'), NULL);
    $breadcrumb[] = l(t('Forums'), 'forums');
    $field_forums = field_get_items('node', $node, 'field_forums');
    if ($field_forums) {
      $data = reset($field_forums);
      $data = $data['taxonomy_term'];
      $breadcrumb[] = l($data->name, $data->path['alias']);
    }
    backdrop_set_breadcrumb($breadcrumb);
    
  }
}

/**
 * Implements hook_views_pre_render().
 */
function borg_forum_views_pre_render(&$view) {
  if ($view->name == 'taxonomy_term') {
    $parents = taxonomy_term_load_parents_all($view->args[0]);
    unset($parents[0]);
    $parents = array_reverse($parents);

    $breadcrumb = array();
    $breadcrumb[] = l(t('Home'), NULL);
    $breadcrumb[] = l(t('Forums'), 'forums');
    if ($parents) {
      foreach ($parents as $parent) {
        $breadcrumb[] = l($parent->name, 'forums/' . $parent->tid);
      }
    }
    backdrop_set_breadcrumb($breadcrumb);
  }
  if ($view->name == 'categories') {
    $breadcrumb = array();
    $breadcrumb[] = l(t('Home'), NULL);
    backdrop_set_breadcrumb($breadcrumb);
  }
}
