<?php
/**
 * @file
 * Module for testing hook_flag_access.
 */

/**
 * Implements hook_flag_access.
 */
function flagaccesstest_flag_access($flag, $entity_id, $action, $account) {
  $mode = config_get('flag.settings', 'FlagHookFlagAccessTestCaseMode');
  if (is_null($mode)) {
    $mode = 'ignore';
  }

  switch ($mode) {
    case 'ignore':
      backdrop_set_message('hook_flag_access: ignore');
      return NULL;

    case 'allow':
      backdrop_set_message('hook_flag_access: allow');
      return TRUE;

    case 'deny':
      backdrop_set_message('hook_flag_access: deny');
      return FALSE;
  }
}
